INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Afghanis,tan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Aland Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Albania',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Algeria',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('American Samoa',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Andorra',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Angola',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Anguilla',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Antarctica',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Antigua And Barbuda',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Argentina',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Armenia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Aruba',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Australia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Austria',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Azerbaijan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bahrain',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bangladesh',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Barbados',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Belarus',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Belgium',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Belize',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Benin',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bermuda',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bhutan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bolivia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bonaire,Sint Eustatius and Saba',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bosnia and Herzegovina',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Botswana',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bouvet Island',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Brazil',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('British Indian Ocean Territory',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Brunei',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bulgaria',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Burkina Faso',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Burundi',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cambodia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cameroon',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Canada',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cape Verde',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cayman Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Central African Republic',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Chad',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Chile',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('China',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Christmas Island',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cocos (Keeling) Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Colombia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Comoros',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Congo',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cook Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Costa Rica',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cote D''Ivoire (Ivory Coast)',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Croatia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cuba',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Curaçao',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cyprus',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Czech Republic',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Democratic Republic of the Congo',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Denmark',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Djibouti',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Dominica',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Dominican Republic',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('East Timor',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ecuador',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Egypt',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('El Salvador',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Equatorial Guinea',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Eritrea',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Estonia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ethiopia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Falkland Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Faroe Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Fiji Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Finland',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('France',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('French Guiana',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('French Polynesia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('French Southern Territories',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Gabon',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Gambia The',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Georgia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Germany',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ghana',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Gibraltar',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Greece',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Greenland',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Grenada',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guadeloupe',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guam',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guatemala',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guernsey and Alderney',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guinea',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guinea-Bissau',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guyana',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Haiti',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Heard Island and McDonald Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Honduras',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Hong Kong S.A.R.',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Hungary',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Iceland',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('India',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Indonesia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Iran',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Iraq',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ireland',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Israel',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Italy',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Jamaica',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Japan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Jersey',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Jordan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kazakhstan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kenya',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kiribati',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kosovo',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kuwait',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kyrgyzstan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Laos',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Latvia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Lebanon',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Lesotho',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Liberia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Libya',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Liechtenstein',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Lithuania',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Luxembourg',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Macau S.A.R.',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Madagascar',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Malawi',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Malaysia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Maldives',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mali',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Malta',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Man (Isle of)',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Marshall Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Martinique',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mauritania',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mauritius',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mayotte',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mexico',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Micronesia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Moldova',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Monaco',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mongolia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Montenegro',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Montserrat',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Morocco',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mozambique',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Myanmar',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Namibia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nauru',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nepal',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Netherlands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('New Caledonia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('New Zealand',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nicaragua',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Niger',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nigeria',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Niue',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Norfolk Island',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('North Korea',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('North Macedonia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Northern Mariana Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Norway',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Oman',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Pakistan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Palau',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Palestinian Territory Occupied',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Panama',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Papua new Guinea',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Paraguay',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Peru',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Philippines',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Pitcairn Island',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Poland',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Portugal',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Puerto Rico',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Qatar',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Reunion',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Romania',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Russia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Rwanda',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Helena',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Kitts And Nevis',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Lucia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Pierre and Miquelon',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Vincent And The Grenadines',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint-Barthelemy',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint-Martin (French part)',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Samoa',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('San Marino',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sao Tome and Principe',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saudi Arabia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Senegal',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Serbia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Seychelles',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sierra Leone',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Singapore',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sint Maarten (Dutch part)',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Slovakia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Slovenia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Solomon Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Somalia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Africa',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Georgia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Korea',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Sudan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Spain',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sri Lanka',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sudan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Suriname',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Svalbard And Jan Mayen Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Swaziland',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sweden',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Switzerland',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Syria',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Taiwan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tajikistan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tanzania',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Thailand',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('The Bahamas',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Togo',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tokelau',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tonga',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Trinidad And Tobago',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tunisia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Turkey',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Turkmenistan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Turks And Caicos Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tuvalu',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Uganda',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ukraine',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United Arab Emirates',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United Kingdom',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United States',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United States Minor Outlying Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Uruguay',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Uzbekistan',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Vanuatu',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Vatican City State (Holy See)',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Venezuela',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Vietnam',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Virgin Islands (British)',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Virgin Islands (US)',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Wallis And Futuna Islands',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Western Sahara',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Yemen',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Zambia',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Zimbabwe',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
