INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Afghanistan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Aland Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Albania',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Algeria',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('American Samoa',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Andorra',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Angola',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Anguilla',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Antarctica',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Antigua And Barbuda',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Argentina',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Armenia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Aruba',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Australia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Austria',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Azerbaijan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bahrain',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bangladesh',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Barbados',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Belarus',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Belgium',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Belize',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Benin',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bermuda',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bhutan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bolivia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bonaire,Sint Eustatius and Saba',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bosnia and Herzegovina',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Botswana',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bouvet Island',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Brazil',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('British Indian Ocean Territory',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Brunei',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bulgaria',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Burkina Faso',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Burundi',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cambodia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cameroon',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Canada',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cape Verde',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cayman Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Central African Republic',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Chad',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Chile',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('China',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Christmas Island',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cocos (Keeling) Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Colombia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Comoros',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Congo',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cook Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Costa Rica',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cote D''Ivoire (Ivory Coast)',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Croatia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cuba',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Curaçao',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cyprus',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Czech Republic',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Democratic Republic of the Congo',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Denmark',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Djibouti',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Dominica',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Dominican Republic',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('East Timor',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ecuador',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Egypt',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('El Salvador',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Equatorial Guinea',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Eritrea',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Estonia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ethiopia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Falkland Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Faroe Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Fiji Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Finland',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('France',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('French Guiana',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('French Polynesia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('French Southern Territories',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Gabon',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Gambia The',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Georgia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Germany',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ghana',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Gibraltar',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Greece',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Greenland',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Grenada',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guadeloupe',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guam',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guatemala',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guernsey and Alderney',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guinea',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guinea-Bissau',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guyana',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Haiti',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Heard Island and McDonald Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Honduras',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Hong Kong S.A.R.',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Hungary',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Iceland',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('India',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Indonesia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Iran',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Iraq',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ireland',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Israel',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Italy',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Jamaica',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Japan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Jersey',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Jordan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kazakhstan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kenya',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kiribati',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kosovo',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kuwait',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kyrgyzstan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Laos',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Latvia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Lebanon',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Lesotho',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Liberia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Libya',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Liechtenstein',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Lithuania',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Luxembourg',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Macau S.A.R.',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Madagascar',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Malawi',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Malaysia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Maldives',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mali',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Malta',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Man (Isle of)',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Marshall Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Martinique',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mauritania',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mauritius',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mayotte',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mexico',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Micronesia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Moldova',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Monaco',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mongolia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Montenegro',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Montserrat',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Morocco',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mozambique',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Myanmar',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Namibia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nauru',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nepal',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Netherlands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('New Caledonia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('New Zealand',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nicaragua',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Niger',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nigeria',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Niue',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Norfolk Island',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('North Korea',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('North Macedonia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Northern Mariana Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Norway',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Oman',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Pakistan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Palau',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Palestinian Territory Occupied',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Panama',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Papua new Guinea',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Paraguay',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Peru',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Philippines',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Pitcairn Island',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Poland',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Portugal',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Puerto Rico',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Qatar',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Reunion',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Romania',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Russia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Rwanda',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Helena',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Kitts And Nevis',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Lucia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Pierre and Miquelon',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Vincent And The Grenadines',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint-Barthelemy',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint-Martin (French part)',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Samoa',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('San Marino',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sao Tome and Principe',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saudi Arabia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Senegal',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Serbia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Seychelles',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sierra Leone',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Singapore',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sint Maarten (Dutch part)',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Slovakia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Slovenia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Solomon Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Somalia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Africa',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Georgia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Korea',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Sudan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Spain',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sri Lanka',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sudan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Suriname',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Svalbard And Jan Mayen Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Swaziland',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sweden',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Switzerland',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Syria',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Taiwan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tajikistan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tanzania',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Thailand',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('The Bahamas',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Togo',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tokelau',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tonga',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Trinidad And Tobago',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tunisia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Turkey',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Turkmenistan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Turks And Caicos Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tuvalu',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Uganda',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ukraine',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United Arab Emirates',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United Kingdom',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United States',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United States Minor Outlying Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Uruguay',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Uzbekistan',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Vanuatu',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Vatican City State (Holy See)',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Venezuela',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Vietnam',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Virgin Islands (British)',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Virgin Islands (US)',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Wallis And Futuna Islands',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Western Sahara',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Yemen',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Zambia',0,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Zimbabwe',0,GETDATE(),GETDATE());
